FROM php:7.4-cli

RUN apt-get update && \
    apt-get install -y \
        git \
        unzip \
        --no-install-recommends && \
   rm -r /var/lib/apt/lists/*

RUN pecl install xdebug && \
    docker-php-ext-enable xdebug

RUN echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.profiler_enable=0" >> /usr/local/etc/php/conf.d/xdebug.ini

VOLUME [ "/app" ]

WORKDIR /app
